# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='created_at',
            new_name='created',
        ),
    ]
