# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='highlighted',
        ),
    ]
