# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name',)},
        ),
        migrations.AddField(
            model_name='ride',
            name='seats_filled',
            field=models.IntegerField(default=0),
        ),
    ]
