# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_remove_ride_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='time',
            field=models.CharField(default='7:30', max_length=255),
            preserve_default=False,
        ),
    ]
