# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20161007_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riders',
            options={'ordering': ('username',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',)},
        ),
        migrations.RemoveField(
            model_name='riders',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
    ]
