# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_ride_pickuplocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='pickupLocation',
        ),
    ]
