# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_remove_ride_pickuplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10.50', max_digits=9),
            preserve_default=False,
        ),
    ]
