# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_auto_20161007_0258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Riders',
        ),
        migrations.AlterField(
            model_name='ride',
            name='seats_filled',
            field=models.IntegerField(),
        ),
    ]
