# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_ride_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
